plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'CamelVSDwarf'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        java {
            exclude 'com/example/camelvsdwarf/audit/entity/**'
            exclude 'com/example/camelvsdwarf/audit/repository/**'
            exclude 'com/example/camelvsdwarf/competitor/dto/**'
            exclude 'com/example/camelvsdwarf/competitor/entity/**'
            exclude 'com/example/camelvsdwarf/competitor/repository/**'
            exclude 'com/example/camelvsdwarf/race/dto/**'
            exclude 'com/example/camelvsdwarf/race/entity/**'
            exclude 'com/example/camelvsdwarf/race/repository/**'
            exclude 'com/example/camelvsdwarf/registration/dto/**'
            exclude 'com/example/camelvsdwarf/registration/entity/**'
            exclude 'com/example/camelvsdwarf/registration/repository/**'
            exclude 'com/example/camelvsdwarf/result/dto/**'
            exclude 'com/example/camelvsdwarf/result/entity/**'
            exclude 'com/example/camelvsdwarf/result/repository/**'
            exclude 'com/example/camelvsdwarf/team/dto/**'
            exclude 'com/example/camelvsdwarf/team/entity/**'
            exclude 'com/example/camelvsdwarf/team/repository/**'
            exclude 'com/example/camelvsdwarf/user/dto/**'
            exclude 'com/example/camelvsdwarf/user/entity/**'
            exclude 'com/example/camelvsdwarf/user/repository/**'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    runtimeOnly 'org.postgresql:postgresql'
    testRuntimeOnly 'com.h2database:h2'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-mongodb-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-mongodb-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}
